# Podfile

# Select the appropriate platform below
platform :ios
# platform :osx

# Add Kiwi as an exclusive dependency for the HelloBDDKiwiTests target
target :HelloBDDKiwiTests, :exclusive => true do
   pod 'Kiwi'
end